version: "3.9"
services:
  flask-backend:
    build: .
    container_name: flask_backend
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=development
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
